binop_separator = "Back"
brace_style = "SameLineWhere"
combine_control_expr = false
edition = "2021"
empty_item_single_line = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
imports_layout = "HorizontalVertical"
merge_imports = true
reorder_impl_items = true
reorder_imports = true
